server.port=8082

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/syncpad_db
spring.datasource.username=maulikmahey
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Jwt Service
jwt.secret=73789020547b7d090d16079f90902f3a2e6797863028881d457018830c7b9953
jwt.expiration=86400000

# Google OAuth Configuration
google.client-id=174530236969-h2rmae878ofutqch5jdp4i3ek32v109q.apps.googleusercontent.com