/**
 * Utility functions for exporting SyncPad documents to Markdown, HTML, and PDF.
 */

function triggerDownload(fileName: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

function sanitizeFileName(title: string): string {
  return (title || 'untitled_document')
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '_')
    .replace(/_+/g, '_')
    .slice(0, 50)
}

export function exportToMarkdown(title: string, content: string, workspaceName?: string, version?: number) {
  const frontmatter = [
    '---',
    `title: "${(title || 'Untitled Document').replace(/"/g, '\\"')}"`,
    workspaceName ? `workspace: "${workspaceName}"` : null,
    version !== undefined ? `version: ${version}` : null,
    `exportedAt: "${new Date().toISOString()}"`,
    'generator: "SyncPad Collaborative Editor"',
    '---',
    '',
    `# ${title || 'Untitled Document'}`,
    '',
    content || ''
  ]
    .filter((line) => line !== null)
    .join('\n')

  const fileName = `${sanitizeFileName(title)}.md`
  triggerDownload(fileName, frontmatter, 'text/markdown;charset=utf-8')
}

export function exportToHtml(title: string, content: string, workspaceName?: string) {
  const safeTitle = title || 'Untitled Document'
  const escapedContent = (content || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')

  // Convert basic markdown paragraphs and newlines to HTML
  const formattedHtml = escapedContent
    .split('\n\n')
    .map((p) => `<p>${p.replace(/\n/g, '<br>')}</p>`)
    .join('\n')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${safeTitle}</title>
  <style>
    :root {
      color-scheme: light dark;
      --bg: #ffffff;
      --fg: #1a1a1a;
      --meta: #666666;
      --border: #eaeaea;
      --code-bg: #f5f5f5;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #121212;
        --fg: #e0e0e0;
        --meta: #888888;
        --border: #2a2a2a;
        --code-bg: #1e1e1e;
      }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 24px;
      line-height: 1.7;
      color: var(--fg);
      background-color: var(--bg);
    }
    h1 {
      font-size: 2rem;
      font-weight: 700;
      letter-spacing: -0.02em;
      margin-bottom: 0.25rem;
    }
    .meta-bar {
      font-size: 0.85rem;
      color: var(--meta);
      padding-bottom: 1.5rem;
      margin-bottom: 2rem;
      border-bottom: 1px solid var(--border);
    }
    .content {
      font-size: 1rem;
    }
    .content p {
      margin-bottom: 1.25rem;
    }
    footer {
      margin-top: 4rem;
      padding-top: 1.5rem;
      border-top: 1px solid var(--border);
      font-size: 0.75rem;
      color: var(--meta);
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>${safeTitle}</h1>
  <div class="meta-bar">
    Exported from <strong>SyncPad</strong> ${workspaceName ? `• Workspace: <em>${workspaceName}</em>` : ''} • ${new Date().toLocaleDateString()}
  </div>
  <div class="content">
    ${formattedHtml}
  </div>
  <footer>
    Document generated by SyncPad Collaborative Suite
  </footer>
</body>
</html>`

  const fileName = `${sanitizeFileName(title)}.html`
  triggerDownload(fileName, html, 'text/html;charset=utf-8')
}

export function exportToPrintPdf(title: string, content: string, workspaceName?: string) {
  const safeTitle = title || 'Untitled Document'
  const printWindow = window.open('', '_blank', 'width=800,height=900')
  if (!printWindow) {
    alert('Please allow popups to export as PDF.')
    return
  }

  const escapedContent = (content || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .split('\n\n')
    .map((p) => `<p style="margin-bottom: 12px; line-height: 1.6;">${p.replace(/\n/g, '<br>')}</p>`)
    .join('')

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${safeTitle}</title>
        <style>
          @page { margin: 20mm; size: A4; }
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #111; padding: 20px; }
          h1 { font-size: 24px; margin-bottom: 6px; }
          .meta { font-size: 11px; color: #666; border-bottom: 1px solid #ccc; padding-bottom: 12px; margin-bottom: 24px; }
          .content { font-size: 13px; }
        </style>
      </head>
      <body>
        <h1>${safeTitle}</h1>
        <div class="meta">SyncPad Export • ${workspaceName ? `Workspace: ${workspaceName} • ` : ''}${new Date().toLocaleString()}</div>
        <div class="content">${escapedContent}</div>
        <script>
          window.onload = function() {
            window.print();
            setTimeout(function() { window.close(); }, 1000);
          };
        </script>
      </body>
    </html>
  `)
  printWindow.document.close()
}
