apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: syncpad

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - ingress.yaml
  - hpa.yaml
  - cert-manager-issuer.yaml
  - backup-cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: syncpad
  app.kubernetes.io/managed-by: kustomize
